---
title: "InterspecificBRI"
author: "Cheyne Springbett"
date: "2023-02-20"
output: pdf_document
---


# Load libraries
```{r}
library(googlesheets4)
library(htmltools)
library(EMMAgeo)


```


# Read in Sheets, Pull in BRI data

```{r reading in google sheets}
sheetnames=sheet_names("https://docs.google.com/spreadsheets/d/1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA")
evalnames=grep("Interspecific BRIs", sheetnames, value=T)

burrow=read_sheet("https://docs.google.com/spreadsheets/d/1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA", sheet=evalnames[1])
```


# Read in Species, BRIs and phi values
# Convert phi sediment granule size to micrometers and show values

```{r}
burrow$Granule_Size_mcm[!is.na(burrow$Granule_Size_phi)]=convert.units(phi=burrow$Granule_Size_phi[!is.na(burrow$Granule_Size_phi)])
```

# Create dataframe

```{r}
briDataFrame=data.frame(species, muvalues, brivalues)
```


#Plotting
```{r}
png("gransize.png")

bivalves=unique(burrow$Species[burrow$Group=="Bivalve"])
octopuses=unique(burrow$Species[burrow$Group=="Octopus"])
crustaceans=unique(burrow$Species[burrow$Group=="Crustacean"])
blues=sample(grep("blue",colors(),value = T))
reds=sample(grep("red",colors(),value=T))
greens=sample(grep("green",colors(),value=T))

plot(Mean_BRI~Granule_Size_mcm,data=burrow,type="n",axes=F,yaxt="n",ylab="log BRI",xlab="Sediment Granule Size (um)",log="xy")
axis(1)
axis(2, at=c(0.001,0.01,0.1,1,10,100), labels = c("0.001","0.01","0.1","1","10","100"))

for (i in 1:length(bivalves)){
  points(Mean_BRI~Granule_Size_mcm,data=burrow[burrow$Species==bivalves[i],],col=blues[i],type="l")
  points(Mean_BRI~Granule_Size_mcm,data=burrow[burrow$Species==bivalves[i],],pch=21,bg=blues[i])
  }

for (i in 1:length(crustaceans)){
  points(Mean_BRI~Granule_Size_mcm,data=burrow[burrow$Species==crustaceans[i],],col=reds[i],type="l")
  points(Mean_BRI~Granule_Size_mcm,data=burrow[burrow$Species==crustaceans[i],],pch=21,bg=reds[i])
  }


for (i in 1:length(octopuses)){
  points(Mean_BRI~Granule_Size_mcm,data=burrow[burrow$Species==octopuses[i],],col=greens[i],type="l")
  points(Mean_BRI~Granule_Size_mcm,data=burrow[burrow$Species==octopuses[i],],pch=21,bg=greens[i])
}

legend(x = "topleft",          # Position
       legend = c("Bivalves", "Crustaceans", "Octopuses"),  # Legend texts
       lty = c(1,1,1),           # Line types
       bty="n",
       col = c("blue","red","green"),           # Line colors
       cex=1,
       lwd = 3)                 # Line width

text(x = 75, y = 10,                # Add Muus label
    substitute(paste(italic( 
    'Muusoctopus 
      leioderma'))),
     cex=.75)

arrows(x0 = 115,                      # Add arrow
       y0 = 14,
       x1 = 200,
       y1 = 14,
       length=0.10,
       lwd = 3)


dev.off()

```





```{r}
plot()



```

#Get number of species
```{r}
list(unique(burrow$Species))
```

